<?php echo PHP_EOL . '<!-- HK2 ScrollTop - START -->' . PHP_EOL; ?>
<div class="scrollTop_div" id="scrollTop_HK2">
    <svg xmlns="http://www.w3.org/2000/svg" class="back-to-top-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 11l5-5m0 0l5 5m-5-5v12" />
    </svg>
</div>
<script src="<?php /* @escapeNotVerified */echo $block->getViewFileUrl('HK2_ScrollTop::js/scrollTop.js'); ?>"></script>
<?php echo '<!-- HK2 ScrollTop - END -->' . PHP_EOL; ?>